### PR TITLE
added poster to git; this version is functional but more images can be added

### PR DESCRIPTION
**Pull request by mccallm1**

### CODE REVIEW

**Review by julianweisbord — CHANGES_REQUESTED** [review]
Can you update this with our most recent revision?

**Comment by mccallm1** [comment]
added final version

**Comment by mccallm1** [comment]
Branch ready to be merged.

**Review by Rodrigmi — APPROVED** [review]
Poster looks good

**Review by julianweisbord — APPROVED** [review]

**Pull request merged**
